apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-container-demo-2
  namespace: alpha-team
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo2
  template:
    metadata:
      labels:
        app: demo2
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 0
            periodSeconds: 1
            failureThreshold: 1
        - name: busybox
          image: busybox
          command: ["sh", "-c", "while true; do echo Hello from busybox; sleep 10; done"]
