apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-service
  namespace: alpha-team
  labels:
    app: alpha-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alpha-service
  template:
    metadata:
      labels:
        app: alpha-service
    spec:
      containers:
      - name: app-container
        image: nginx:1.21
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        # Liveness Probe - Checks if the container is running properly
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        # Readiness Probe - Checks if the container is ready to serve traffic
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        # Startup Probe - Gives extra time for slow startups before liveness kicks in
        startupProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          periodSeconds: 5
          failureThreshold: 30  # Allows up to 150s (30 * 5s) for startup
