apiVersion: v1
kind: ResourceQuota
metadata:
  name: basic-quota
  namespace: alpha-team
spec:
  hard:
    requests.cpu: "2"               # Total requested CPU must not exceed 2 cores
    limits.cpu: "4"                 # Total CPU limit must not exceed 4 cores
    requests.memory: "4Gi"          # Total requested memory must not exceed 4Gi
    limits.memory: "8Gi"            # Total memory limit must not exceed 8Gi
    requests.ephemeral-storage: "10Gi" # Optional: restrict scratch disk usage
    limits.ephemeral-storage: "20Gi"
    pods: "20"                      # Max 20 pods in this namespace

