apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: triple-container-app
  namespace: alpha-team
spec:
  serviceName: "triple-app"
  replicas: 2
  selector:
    matchLabels:
      app: triple-app
  template:
    metadata:
      labels:
        app: triple-app
    spec:
      containers:
        - name: web
          image: nginx:1.25
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 1

        - name: worker
          image: busybox
          command: ["sh", "-c", "while true; do echo Working...; sleep 10; done"]
          livenessProbe:
            exec:
              command: ["sh", "-c", "echo alive"]
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 2
          readinessProbe:
            exec:
              command: ["sh", "-c", "echo ready"]
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 1

        - name: sidecar
          image: alpine
          command: ["sh", "-c", "while true; do echo Sidecar logs...; sleep 15; done"]
          livenessProbe:
            exec:
              command: ["sh", "-c", "echo OK"]
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 2
          readinessProbe:
            exec:
              command: ["sh", "-c", "echo OK"]
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 1

